version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
